### ISSUE TITLE
Tokens should display health info

### ISSUE THREAD

**Issue by Lokathor** [Strifepad/Strifepad#1]
When a token has info on both current and maximum hit points, it should display the creature's current injury level even if the exact current and maximum hit points aren't being displayed to the players. Injury levels are as follows:
- Level (minimum percent of health missing)
- Uninjured (0%)
- Barely scratched (1%)
- Slightly injured (25%) 
- Injured (50%)
- Heavily injured (75%)
- Critically injured (90%)

**Comment by Cosban** [comment]
no
